spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Fender@123}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
server.forward-headers-strategy=framework
logging.level.org.springframework.security=DEBUG
logging.level.com.SpringBootMVC.ExpensesTracker=DEBUG
